spring.application.name=Proyecto

# PUERTO DEL SERVIDOR
server.port=8000

# CONFIGURACION POSTGRESQL
spring.datasource.url=jdbc:postgresql://localhost:5432/logiflow_db
spring.datasource.username=postgres
spring.datasource.password=arlus

# DRIVER POSTGRESQL
spring.datasource.driver-class-name=org.postgresql.Driver

# CONFIGURACION JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update

# Mostrar consultas SQL en consola
spring.jpa.show-sql=true

# Formatear SQL en consola
spring.jpa.properties.hibernate.format_sql=true

# Dialecto PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# CONFIGURACION LOMBOK (opcional)
spring.main.allow-circular-references=true

# JWT
jwt.secret=miclavesupersecretaparajwtsistema2026segura