spring.application.name=Proyecto

# PUERTO DEL SERVIDOR
server.port=8000

# CONFIGURACION POSTGRESQL
spring.datasource.url=jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.yoxcfdfddrhiqcfqkglw
spring.datasource.password=proyecto2026

# DRIVER POSTGRESQL
spring.datasource.driver-class-name=org.postgresql.Driver

# CONFIGURACION JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update

# Mostrar consultas SQL en consola
spring.jpa.show-sql=true

# Formatear SQL en consola
spring.jpa.properties.hibernate.format_sql=true

# Dialecto PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# CONFIGURACION LOMBOK (opcional)
spring.main.allow-circular-references=true

# JWT
jwt.secret=miclavesupersecretaparajwtsistema2026segura

# MERCADO PAGO
mercadopago.access-token=${MERCADO_PAGO_ACCES_TOKEN}